version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./production.env
    depends_on:
      - db

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=priyanshu
      - MONGO_INITDB_ROOT_PASSWORD=priyanshu123
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
      - EDGE_PORT=4566
      - PERSISTENCE=1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    depends_on:
      - app

volumes:
  mongo-data:
  localstack_data: